// src/components/BranchMLOFilters.jsx
import React from "react";

const BranchMLOFilters = ({
  filters,
  availableBranches,
  availableMLOs,
  onFilterChange,
}) => {
  const handleClear = () => {
    onFilterChange("branch", "");
    onFilterChange("mlo", "");
  };

  return (
    <div id="branch-mlo-filters" className="filter-wrapper">
      <span className="filter-label">Branch/MLO Filters:</span>

      <select
        value={filters.branch}
        onChange={(e) => onFilterChange("branch", e.target.value)}
        className="filter-select"
      >
        <option value="">All Branches</option>
        {availableBranches.map((branch) => (
          <option key={branch} value={branch}>
            {branch}
          </option>
        ))}
      </select>

      <select
        value={filters.mlo}
        onChange={(e) => onFilterChange("mlo", e.target.value)}
        className="filter-select"
      >
        <option value="">All MLOs</option>
        {availableMLOs.map((mlo) => (
          <option key={mlo} value={mlo}>
            {mlo}
          </option>
        ))}
      </select>

      {(filters.branch || filters.mlo) && (
        <button onClick={handleClear} className="filter-clear-button">
          Clear Branch & MLO
        </button>
      )}
    </div>
  );
};

export default BranchMLOFilters;

// src/components/BranchMLOFilters.vue
<template>
  <section class="filter-card">
    <div class="filter-card__header">
      <p class="filter-card__eyebrow">Branch + MLO</p>
      <h2 class="filter-card__title">Pipeline Assignment</h2>
    </div>

    <div class="filter-row">
      <label class="field-group">
        <span class="field-label">Branch</span>
        <select
          :value="filters.branch"
          class="field-control"
          @change="$emit('filter-change', 'branch', $event.target.value)"
        >
          <option value="">All Branches</option>
          <option
            v-for="branch in availableBranches"
            :key="branch"
            :value="branch"
          >
            {{ branch }}
          </option>
        </select>
      </label>

      <label class="field-group">
        <span class="field-label">MLO</span>
        <select
          :value="filters.mlo"
          class="field-control"
          @change="$emit('filter-change', 'mlo', $event.target.value)"
        >
          <option value="">All MLOs</option>
          <option v-for="mlo in availableMLOs" :key="mlo" :value="mlo">
            {{ mlo }}
          </option>
        </select>
      </label>

      <button
        v-if="filters.branch || filters.mlo"
        type="button"
        class="secondary-button"
        @click="handleClear"
      >
        Clear Branch + MLO
      </button>
    </div>
  </section>
</template>

<script>
export default {
  name: "BranchMLOFilters",
  props: {
    filters: {
      type: Object,
      required: true,
    },
    availableBranches: {
      type: Array,
      default: () => [],
    },
    availableMLOs: {
      type: Array,
      default: () => [],
    },
  },
  emits: ["filter-change"],
  methods: {
    handleClear() {
      this.$emit("filter-change", "branch", "");
      this.$emit("filter-change", "mlo", "");
    },
  },
};
</script>
