// src/components/BranchMLOModal.vue
<template>
  <div v-if="branchModalData" class="modal-overlay" @click="$emit('close')">
    <div class="modal-card modal-card--wide modal-card--mlo" @click.stop>
      <header class="modal-card__header">
        <h2>{{ branchModalData.branchName }} - Loan Officers</h2>
        <button
          type="button"
          class="modal-close-button"
          @click="$emit('close')"
        >
          ×
        </button>
      </header>

      <div class="modal-card__summary modal-card__summary--dual">
        <span
          >Total Loans <strong>{{ branchModalData.totalLoans }}</strong></span
        >
        <span
          >Loan Officers
          <strong>{{ branchModalData.mloData.length }}</strong></span
        >
      </div>

      <div class="modal-card__content">
        <div v-if="sortedMloData.length === 0" class="empty-state">
          No loan officers found.
        </div>
        <table v-else class="data-table">
          <thead>
            <tr>
              <th v-for="column in columns" :key="column.key">
                <button
                  type="button"
                  class="sort-button"
                  @click="handleSort(column.key)"
                >
                  {{ column.label }}
                  <span class="sort-button__indicator">
                    {{
                      sortColumn === column.key
                        ? sortDirection === "asc"
                          ? "↑"
                          : "↓"
                        : "↕"
                    }}
                  </span>
                </button>
              </th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="mlo in sortedMloData" :key="mlo.mloId">
              <td>
                <button
                  type="button"
                  class="loan-link-button"
                  @click="
                    $emit('mlo-click', branchModalData.branchName, mlo.mloId)
                  "
                >
                  {{ mlo.mloId }}
                </button>
              </td>
              <td>{{ mlo.total }}</td>
              <td>{{ mlo.passed }}</td>
              <td>{{ mlo.warned }}</td>
              <td>{{ mlo.failed }}</td>
              <td>{{ mlo.passRate }}%</td>
              <td>{{ mlo.warnRate }}%</td>
              <td>{{ mlo.failRate }}%</td>
            </tr>
          </tbody>
        </table>
      </div>

      <footer class="modal-card__footer">
        <button type="button" class="secondary-button" @click="$emit('close')">
          Close
        </button>
      </footer>
    </div>
  </div>
</template>

<script>
export default {
  name: "BranchMLOModal",
  props: {
    branchModalData: {
      type: Object,
      default: null,
    },
  },
  emits: ["close", "mlo-click"],
  data() {
    return {
      columns: [
        { key: "mloId", label: "MLO NMLS ID" },
        { key: "total", label: "Total Loans" },
        { key: "passed", label: "Passed" },
        { key: "warned", label: "Warnings" },
        { key: "failed", label: "Failed" },
        { key: "passRate", label: "Pass Rate" },
        { key: "warnRate", label: "Warn Rate" },
        { key: "failRate", label: "Fail Rate" },
      ],
      sortColumn: "total",
      sortDirection: "desc",
    };
  },
  computed: {
    sortedMloData() {
      if (!this.branchModalData?.mloData) {
        return [];
      }

      return [...this.branchModalData.mloData].sort((left, right) => {
        const leftValue = ["passRate", "warnRate", "failRate"].includes(
          this.sortColumn,
        )
          ? Number.parseFloat(left[this.sortColumn])
          : left[this.sortColumn];
        const rightValue = ["passRate", "warnRate", "failRate"].includes(
          this.sortColumn,
        )
          ? Number.parseFloat(right[this.sortColumn])
          : right[this.sortColumn];

        if (leftValue < rightValue) {
          return this.sortDirection === "asc" ? -1 : 1;
        }
        if (leftValue > rightValue) {
          return this.sortDirection === "asc" ? 1 : -1;
        }
        return 0;
      });
    },
  },
  methods: {
    handleSort(column) {
      if (this.sortColumn === column) {
        this.sortDirection = this.sortDirection === "asc" ? "desc" : "asc";
        return;
      }

      this.sortColumn = column;
      this.sortDirection = "desc";
    },
  },
};
</script>

// src/components/BranchMLOModal.jsx
import React, { useState, useMemo } from "react";

const BranchMLOModal = ({ branchModalData, onClose, onMLOClick }) => {
  const [sortColumn, setSortColumn] = useState("total");
  const [sortDirection, setSortDirection] = useState("desc");

  const handleSort = (column) => {
    if (sortColumn === column) {
      setSortDirection(sortDirection === "asc" ? "desc" : "asc");
    } else {
      setSortColumn(column);
      setSortDirection("desc");
    }
  };

  const sortedMloData = useMemo(() => {
    if (!branchModalData?.mloData) return [];

    const sorted = [...branchModalData.mloData].sort((a, b) => {
      let aVal, bVal;

      switch (sortColumn) {
        case "mloId":
          aVal = a.mloId;
          bVal = b.mloId;
          break;
        case "total":
          aVal = a.total;
          bVal = b.total;
          break;
        case "passed":
          aVal = a.passed;
          bVal = b.passed;
          break;
        case "warned":
          aVal = a.warned;
          bVal = b.warned;
          break;
        case "failed":
          aVal = a.failed;
          bVal = b.failed;
          break;
        case "passRate":
          aVal = parseFloat(a.passRate);
          bVal = parseFloat(b.passRate);
          break;
        case "warnRate":
          aVal = parseFloat(a.warnRate);
          bVal = parseFloat(b.warnRate);
          break;
        case "failRate":
          aVal = parseFloat(a.failRate);
          bVal = parseFloat(b.failRate);
          break;
        default:
          return 0;
      }

      if (aVal < bVal) return sortDirection === "asc" ? -1 : 1;
      if (aVal > bVal) return sortDirection === "asc" ? 1 : -1;
      return 0;
    });

    return sorted;
  }, [branchModalData?.mloData, sortColumn, sortDirection]);

  const SortIcon = ({ column }) => {
    if (sortColumn !== column) {
      return (
        <svg
          className="w-4 h-4 ml-1 text-slate-400"
          fill="currentColor"
          viewBox="0 0 20 20"
        >
          <path d="M5 12l5 5 5-5H5zm10-4L10 3 5 8h10z" />
        </svg>
      );
    }
    return sortDirection === "asc" ? (
      <svg
        className="w-4 h-4 ml-1 text-blue-600"
        fill="currentColor"
        viewBox="0 0 20 20"
      >
        <path d="M5 12l5 5 5-5H5z" opacity="0.3" />
        <path d="M15 8L10 3 5 8h10z" />
      </svg>
    ) : (
      <svg
        className="w-4 h-4 ml-1 text-blue-600"
        fill="currentColor"
        viewBox="0 0 20 20"
      >
        <path d="M15 8L10 3 5 8h10z" opacity="0.3" />
        <path d="M5 12l5 5 5-5H5z" />
      </svg>
    );
  };

  if (!branchModalData) return null;

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-black bg-opacity-50 p-4"
      onClick={onClose}
    >
      <div
        className="bg-white rounded-2xl w-full max-w-4xl shadow-2xl overflow-hidden"
        style={{ maxHeight: "calc(100vh - 2rem)" }}
        onClick={(e) => e.stopPropagation()}
      >
        <div className="flex items-center justify-between p-6 border-b border-slate-200 bg-white">
          <h2 className="text-2xl font-bold text-slate-900 pr-4">
            {branchModalData.branchName} - Loan Officers
          </h2>
          <button
            onClick={onClose}
            className="p-2 hover:bg-slate-100 rounded-lg transition-colors flex-shrink-0"
            aria-label="Close modal"
          >
            <svg
              className="w-6 h-6 text-slate-600"
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M6 18L18 6M6 6l12 12"
              />
            </svg>
          </button>
        </div>

        <div className="p-6 bg-blue-50 border-b border-slate-200">
          <p className="text-lg">
            <span className="font-semibold text-slate-700">Total Loans: </span>
            <span className="font-bold text-blue-600 text-xl">
              {branchModalData.totalLoans}
            </span>
            <span className="ml-4 font-semibold text-slate-700">
              Loan Officers:{" "}
            </span>
            <span className="font-bold text-blue-600 text-xl">
              {branchModalData.mloData.length}
            </span>
          </p>
        </div>

        <div
          className="overflow-auto"
          style={{ maxHeight: "calc(100vh - 20rem)" }}
        >
          {branchModalData.mloData.length === 0 ? (
            <div className="text-center py-12 text-slate-500 text-lg">
              No loan officers found
            </div>
          ) : (
            <table className="w-full">
              <thead className="bg-slate-200 sticky top-0">
                <tr>
                  <th
                    className="px-4 py-3 text-left text-sm font-bold text-slate-700 cursor-pointer hover:bg-slate-300 transition-colors"
                    onClick={() => handleSort("mloId")}
                  >
                    <div className="flex items-center">
                      MLO NMLS ID
                      <SortIcon column="mloId" />
                    </div>
                  </th>
                  <th
                    className="px-4 py-3 text-center text-sm font-bold text-slate-700 cursor-pointer hover:bg-slate-300 transition-colors"
                    onClick={() => handleSort("total")}
                  >
                    <div className="flex items-center justify-center">
                      Total Loans
                      <SortIcon column="total" />
                    </div>
                  </th>
                  <th
                    className="px-4 py-3 text-center text-sm font-bold text-slate-700 cursor-pointer hover:bg-slate-300 transition-colors"
                    onClick={() => handleSort("passed")}
                  >
                    <div className="flex items-center justify-center">
                      Passed
                      <SortIcon column="passed" />
                    </div>
                  </th>
                  <th
                    className="px-4 py-3 text-center text-sm font-bold text-slate-700 cursor-pointer hover:bg-slate-300 transition-colors"
                    onClick={() => handleSort("warned")}
                  >
                    <div className="flex items-center justify-center">
                      Warnings
                      <SortIcon column="warned" />
                    </div>
                  </th>
                  <th
                    className="px-4 py-3 text-center text-sm font-bold text-slate-700 cursor-pointer hover:bg-slate-300 transition-colors"
                    onClick={() => handleSort("failed")}
                  >
                    <div className="flex items-center justify-center">
                      Failed
                      <SortIcon column="failed" />
                    </div>
                  </th>
                  <th
                    className="px-4 py-3 text-center text-sm font-bold text-slate-700 cursor-pointer hover:bg-slate-300 transition-colors"
                    onClick={() => handleSort("passRate")}
                  >
                    <div className="flex items-center justify-center">
                      Pass Rate
                      <SortIcon column="passRate" />
                    </div>
                  </th>
                  <th
                    className="px-4 py-3 text-center text-sm font-bold text-slate-700 cursor-pointer hover:bg-slate-300 transition-colors"
                    onClick={() => handleSort("warnRate")}
                  >
                    <div className="flex items-center justify-center">
                      Warn Rate
                      <SortIcon column="warnRate" />
                    </div>
                  </th>
                  <th
                    className="px-4 py-3 text-center text-sm font-bold text-slate-700 cursor-pointer hover:bg-slate-300 transition-colors"
                    onClick={() => handleSort("failRate")}
                  >
                    <div className="flex items-center justify-center">
                      Fail Rate
                      <SortIcon column="failRate" />
                    </div>
                  </th>
                </tr>
              </thead>
              <tbody className="bg-white">
                {sortedMloData.map((mlo) => (
                  <tr
                    key={mlo.mloId}
                    className="border-b border-slate-200 hover:bg-slate-50"
                  >
                    <td className="px-4 py-3 text-sm">
                      <button
                        onClick={() =>
                          onMLOClick(branchModalData.branchName, mlo.mloId)
                        }
                        className="font-semibold text-blue-600 hover:text-blue-800 hover:underline cursor-pointer"
                      >
                        {mlo.mloId}
                      </button>
                    </td>
                    <td className="px-4 py-3 text-sm text-center text-slate-700">
                      {mlo.total}
                    </td>
                    <td className="px-4 py-3 text-sm text-center text-emerald-600 font-semibold">
                      {mlo.passed}
                    </td>
                    <td className="px-4 py-3 text-sm text-center text-amber-600 font-semibold">
                      {mlo.warned}
                    </td>
                    <td className="px-4 py-3 text-sm text-center text-red-600 font-semibold">
                      {mlo.failed}
                    </td>
                    <td className="px-4 py-3 text-sm text-center text-slate-700">
                      {mlo.passRate}%
                    </td>
                    <td className="px-4 py-3 text-sm text-center text-slate-700">
                      {mlo.warnRate}%
                    </td>
                    <td className="px-4 py-3 text-sm text-center text-slate-700">
                      {mlo.failRate}%
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          )}
        </div>

        <div className="flex items-center justify-end p-4 border-t border-slate-200 bg-slate-50">
          <button
            onClick={onClose}
            className="px-6 py-2 bg-slate-600 text-white rounded-lg hover:bg-slate-700 transition-colors font-semibold"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
};

export default BranchMLOModal;
