// src/components/DashboardHeader.jsx
import React from "react";
import { Shield } from "lucide-react";

const DashboardHeader = ({ portfolioStats }) => {
  return (
    <div className="mb-6">
      <div className="flex items-center justify-between mb-4">
        <div>
          <h1 className="text-4xl font-bold text-slate-900 mb-2 flex items-center gap-3">
            <Shield className="w-10 h-10 text-blue-600" />
            Mortgage Compliance Dashboard - Iowa
          </h1>
          <p className="text-slate-600 text-lg">
            Automated regulatory audit analysis across {portfolioStats.total}{" "}
            loan files
          </p>
        </div>
      </div>
    </div>
  );
};

export default DashboardHeader;

// src/components/DashboardHeader.vue
<template>
  <header class="dashboard-header">
    <div>
      <p class="eyebrow">Iowa Portfolio Overview</p>
      <h1 class="dashboard-title">
        <Shield class="dashboard-title__icon" />
        <span>Mortgage Compliance Dashboard - Iowa</span>
      </h1>
      <p class="dashboard-subtitle">
        Automated regulatory audit analysis across {{ portfolioStats.total }}
        loan files
      </p>
    </div>
  </header>
</template>

<script>
import { Shield } from "lucide-vue-next";

export default {
  name: "DashboardHeader",
  components: {
    Shield,
  },
  props: {
    portfolioStats: {
      type: Object,
      required: true,
    },
  },
};
</script>
