// src/components/LoanListModal.vue
<template>
  <div v-if="modalData" class="modal-overlay" @click="$emit('close')">
    <div class="modal-card modal-card--wide" @click.stop>
      <header class="modal-card__header">
        <h2>{{ modalData.title }}</h2>
        <button
          type="button"
          class="modal-close-button"
          @click="$emit('close')"
        >
          ×
        </button>
      </header>

      <div class="modal-card__summary">
        <span>Total Loans</span>
        <strong>{{ modalData.loans.length }}</strong>
      </div>

      <div class="modal-card__content">
        <div v-if="modalData.loans.length === 0" class="empty-state">
          No loans found with this status.
        </div>
        <table v-else class="data-table">
          <thead>
            <tr>
              <th>Loan ID</th>
              <th>Branch ID</th>
              <th>MLO NMLS</th>
              <th>Type</th>
              <th>Term</th>
              <th>Amortization</th>
              <th>Purpose</th>
              <th>Occupancy</th>
              <th>Amount</th>
              <th>Status</th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="loan in modalData.loans" :key="loan.id">
              <td>
                <div class="loan-link-cluster">
                  <button
                    type="button"
                    class="loan-link-button"
                    @click="$emit('loan-click', loan.id)"
                  >
                    {{ loan.id }}
                  </button>
                  <button
                    type="button"
                    class="icon-chip"
                    title="View PDF"
                    @click="$emit('open-image-modal', sampleDocument)"
                  >
                    PDF
                  </button>
                  <button
                    type="button"
                    class="icon-chip icon-chip--brand"
                    title="Open in RegCheck"
                    @click="$emit('open-image-modal', sampleDocument)"
                  >
                    RC
                  </button>
                </div>
              </td>
              <td>{{ loan.branchId }}</td>
              <td>{{ loan.mloNmlsId }}</td>
              <td>{{ loan.loanType }}</td>
              <td>{{ loan.loanTerm }}y</td>
              <td>{{ loan.amortizationType }}</td>
              <td>{{ loan.purpose }}</td>
              <td>{{ loan.occupancy }}</td>
              <td>${{ loan.amount.toLocaleString() }}</td>
              <td>
                <span :class="getStatusColor(modalData.status)">
                  <component
                    :is="statusIcon(modalData.status)"
                    class="status-badge__icon"
                  />
                  {{ modalData.status }}
                </span>
              </td>
            </tr>
          </tbody>
        </table>
      </div>

      <footer class="modal-card__footer">
        <button type="button" class="secondary-button" @click="$emit('close')">
          Close
        </button>
      </footer>
    </div>
  </div>
</template>

<script>
import { AlertCircle, AlertTriangle, CheckCircle } from "lucide-vue-next";
import sampleDocument from "../assets/sample-pdf.jpg";
import { getStatusColor } from "../utils/statusHelpers";

export default {
  name: "LoanListModal",
  props: {
    modalData: {
      type: Object,
      default: null,
    },
  },
  emits: ["close", "loan-click", "open-image-modal"],
  methods: {
    getStatusColor,
    statusIcon(status) {
      if (status === "pass") return CheckCircle;
      if (status === "warn") return AlertTriangle;
      return AlertCircle;
    },
  },
  data() {
    return {
      sampleDocument,
    };
  },
};
</script>

// src/components/LoanListModal.jsx
import React from "react";
import { CheckCircle, AlertTriangle, AlertCircle } from "lucide-react";
import { getStatusColor } from "../utils/statusHelpers";
import sampleDocument from "../assets/sample-pdf.jpg";

const getStatusIcon = (status) => {
  switch (status) {
    case "pass":
      return <CheckCircle className="w-4 h-4" />;
    case "warn":
      return <AlertTriangle className="w-4 h-4" />;
    case "fail":
      return <AlertCircle className="w-4 h-4" />;
    default:
      return <AlertCircle className="w-4 h-4" />;
  }
};

const LoanListModal = ({
  modalData,
  onClose,
  onLoanClick,
  onOpenImageModal,
}) => {
  if (!modalData) return null;

  const handleLoanLinkClick = (loanId) => {
    onLoanClick(loanId);
  };

  const handlePdfClick = () => {
    onOpenImageModal(sampleDocument);
  };

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-black bg-opacity-50 p-4"
      onClick={onClose}
    >
      <div
        className="bg-white rounded-2xl w-full max-w-6xl shadow-2xl overflow-hidden modal-container"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="flex items-center justify-between p-6 border-b border-slate-200 bg-white">
          <h2 className="text-2xl font-bold text-slate-900 pr-4">
            {modalData.title}
          </h2>
          <button
            onClick={onClose}
            className="p-2 hover:bg-slate-100 rounded-lg transition-colors flex-shrink-0"
            aria-label="Close modal"
          >
            <svg
              className="w-6 h-6 text-slate-600"
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M6 18L18 6M6 6l12 12"
              />
            </svg>
          </button>
        </div>

        <div className="p-6 bg-blue-50 border-b border-slate-200">
          <p className="text-lg">
            <span className="font-semibold text-slate-700">Total Loans: </span>
            <span className="font-bold text-blue-600 text-xl">
              {modalData.loans.length}
            </span>
          </p>
        </div>

        <div className="overflow-auto modal-content-scroll">
          {modalData.loans.length === 0 ? (
            <div className="text-center py-12 text-slate-500 text-lg">
              No loans found with this status
            </div>
          ) : (
            <table className="w-full">
              <thead className="bg-slate-200 sticky top-0">
                <tr>
                  <th className="px-4 py-3 text-left text-sm font-bold text-slate-700 border-b-2 border-slate-300 bg-slate-200">
                    Loan ID
                  </th>
                  <th className="px-4 py-3 text-left text-sm font-bold text-slate-700 border-b-2 border-slate-300 bg-slate-200">
                    Branch ID
                  </th>
                  <th className="px-4 py-3 text-left text-sm font-bold text-slate-700 border-b-2 border-slate-300 bg-slate-200">
                    MLO NMLS
                  </th>
                  <th className="px-4 py-3 text-left text-sm font-bold text-slate-700 border-b-2 border-slate-300 bg-slate-200">
                    Type
                  </th>
                  <th className="px-4 py-3 text-left text-sm font-bold text-slate-700 border-b-2 border-slate-300 bg-slate-200">
                    Term
                  </th>
                  <th className="px-4 py-3 text-left text-sm font-bold text-slate-700 border-b-2 border-slate-300 bg-slate-200">
                    Amortization
                  </th>
                  <th className="px-4 py-3 text-left text-sm font-bold text-slate-700 border-b-2 border-slate-300 bg-slate-200">
                    Purpose
                  </th>
                  <th className="px-4 py-3 text-left text-sm font-bold text-slate-700 border-b-2 border-slate-300 bg-slate-200">
                    Occupancy
                  </th>
                  <th className="px-4 py-3 text-left text-sm font-bold text-slate-700 border-b-2 border-slate-300 bg-slate-200">
                    Amount
                  </th>
                  <th className="px-4 py-3 text-left text-sm font-bold text-slate-700 border-b-2 border-slate-300 bg-slate-200">
                    Status
                  </th>
                </tr>
              </thead>
              <tbody className="bg-white">
                {modalData.loans.map((loan) => (
                  <tr
                    key={loan.id}
                    className="border-b border-slate-200 hover:bg-slate-50"
                  >
                    <td className="px-4 py-3 text-sm whitespace-nowrap">
                      <div className="flex items-center gap-2">
                        <button
                          onClick={() => handleLoanLinkClick(loan.id)}
                          className="loan-link-button"
                        >
                          {loan.id}
                        </button>
                        <button
                          onClick={handlePdfClick}
                          className="p-1 hover:bg-red-50 rounded transition-colors"
                          title="View PDF"
                        >
                          <svg
                            className="w-4 h-4 text-red-600"
                            fill="currentColor"
                            viewBox="0 0 24 24"
                          >
                            <path d="M14,2H6A2,2 0 0,0 4,4V20A2,2 0 0,0 6,22H18A2,2 0 0,0 20,20V8L14,2M18.5,9L13,3.5V9H18.5M6,20V4H11V10H18V20H6M7,11H9V18H7V11M10,11H12A2,2 0 0,1 14,13V15A2,2 0 0,1 12,17H10V11M12,15V13H11V15H12M15,11H17V13H19V15H17V18H15V11Z" />
                          </svg>
                        </button>
                        <button
                          onClick={() =>
                            console.log("Logo clicked for", loan.id)
                          }
                          className="p-1 hover:bg-blue-50 rounded transition-colors"
                          title="Open in RegCheck"
                        >
                          <svg
                            className="w-4 h-4"
                            viewBox="0 0 24 24"
                            fill="none"
                          >
                            <path
                              d="M12 2L3 7L12 12L21 7L12 2Z"
                              fill="#1e40af"
                            />
                            <path
                              d="M3 17L12 22L21 17L12 12L3 17Z"
                              fill="#f97316"
                            />
                            <path
                              d="M12 2L3 7V17L12 12V2Z"
                              fill="#1e40af"
                              fillOpacity="0.8"
                            />
                            <path
                              d="M12 2L21 7V17L12 12V2Z"
                              fill="#1e40af"
                              fillOpacity="0.6"
                            />
                          </svg>
                        </button>
                      </div>
                    </td>
                    <td className="px-4 py-3 text-sm text-slate-700 whitespace-nowrap">
                      {loan.branchId}
                    </td>
                    <td className="px-4 py-3 text-sm text-slate-700 whitespace-nowrap">
                      {loan.mloNmlsId}
                    </td>
                    <td className="px-4 py-3 text-sm text-slate-700 whitespace-nowrap">
                      {loan.loanType}
                    </td>
                    <td className="px-4 py-3 text-sm text-slate-700 whitespace-nowrap">
                      {loan.loanTerm}y
                    </td>
                    <td className="px-4 py-3 text-sm text-slate-700 whitespace-nowrap">
                      {loan.amortizationType}
                    </td>
                    <td className="px-4 py-3 text-sm text-slate-700 whitespace-nowrap">
                      {loan.purpose}
                    </td>
                    <td className="px-4 py-3 text-sm text-slate-700 whitespace-nowrap">
                      {loan.occupancy}
                    </td>
                    <td className="px-4 py-3 text-sm text-slate-700 whitespace-nowrap">
                      ${loan.amount.toLocaleString()}
                    </td>
                    <td className="px-4 py-3">
                      <span
                        className={`px-3 py-1 rounded-full text-xs font-semibold inline-flex items-center gap-1 whitespace-nowrap ${getStatusColor(modalData.status)}`}
                      >
                        {getStatusIcon(modalData.status)}
                        {modalData.status}
                      </span>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          )}
        </div>

        <div className="flex items-center justify-end p-4 border-t border-slate-200 bg-slate-50">
          <button
            onClick={onClose}
            className="px-6 py-2 bg-slate-600 text-white rounded-lg hover:bg-slate-700 transition-colors font-semibold"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
};

export default LoanListModal;
